Feature/save workouts
fricabadha/sport_bot pull request #2
Opened 2023-03-02 22:39 UTC by fricabadha

2023-03-02 23:21 UTC, TendTo requested changes
Sarebbero da aggiungere tutti i type-hint sia ai parametri delle funzioni che ai valor di ritorno delle stesse.

2023-03-02 23:21 UTC, TendTo commented on SportBot.py
> +    "CREATE TABLE IF NOT EXISTS goals (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT, distance FLOAT)")
Non è molto elegante mettere questo tipo di operazioni al livello base, dato che così sarebbero eseguite anche ogni volta che qualcuno importa questo modulo. Conviene racchiuderle in una funzione, anche del bot, e chiamarla esplicitamente, se lo si ritiene necessario.

2023-03-02 23:21 UTC, TendTo commented on SportBot.py
> +conn = mydb.cursor()
Se le chiamate al database non sono troppo frequenti, non è una buona pratica lasciare la connessione aperta per troppo tempo, anche perchè potrebbe verificarsi anche un timeout. Piuttosto è meglio ricreare la connessione e il cursore nel momento del bisogno, e chiuderlo subito dopo.

2023-03-02 23:21 UTC, TendTo commented on main.py
> +        update.message.reply_text("Totale ore: %s,\nMedia ore: %s,\nTotale km: %s,\nMedia km: %s,\nVelocità media: %s,\nTotale allenamenti: %s" % (res["tot_ore"], res["media_ore"], res["tot_km"], res
Ti consiglierei di utilizzare le [f-string](https://realpython.com/python-f-strings/).

2023-03-13 11:42 UTC, fricabadha commented on SportBot.py
> +conn = mydb.cursor()
Al momento ho messo la connessione al costruttore, se ci sono problemi di timeout implementerò la soluzione che consigli.

2023-03-13 11:46 UTC, gtozz requested changes

2023-03-13 11:46 UTC, gtozz commented on SportBot.py
> +            print("Tempo: ", workout[2], self.convert_time_in_sec(workout[2]))
These print may be removed or replaced with a [logger](https://docs.python.org/3/library/logging.html)

2023-03-13 11:52 UTC, gtozz approved these changes

2023-03-22 17:19 UTC, merged